### PR TITLE
WIP: Updating to babel 6

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Hello @jedireza,
I'm trying to make lab work with babel 6, 
looking for that I end up on your repo, with this example.
Thought that was better to start with this and try to update.
However, doing this, I get that trace

```
lab -t 100 -S -T ./node_modules/lab-babel ./test/src/

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.require.extensions.(anonymous function) [as .js] (XXXXXX/lab-es6/node_modules/lab/lib/coverage.js:36:28)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at XXXXx/lab-es6/node_modules/lab/lib/cli.js:106:25
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (XXXXx/lab-es6/node_modules/lab/lib/cli.js:102:19)
    at Object.exports.run (XXXXx/lab-es6/node_modules/lab/lib/cli.js:51:31)
    at Object.<anonymous> (XXXXx/lab-es6/node_modules/lab/bin/lab:5:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.
```

Maybe you have some idea about what's behind this, and how to solve it :)

thanks in advance!

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
here is some of links I stumbled upon:
- http://stackoverflow.com/questions/33604470/unexpected-token-import-in-nodejs5-and-babel
- https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.om0tj0ktu

**Comment by jedireza** [comment]
Thanks for opening an issue. This repo was created a while back, just as an example. It's probably best to use [`lab-babel`](https://github.com/nlf/lab-babel/) instead.

**Comment by AdrieanKhisbe** [comment]
indeed it was more a question. :) 
The point of this was to see how to use lab-babel with babel-6, taking your hello-lab-babel as an example.

**Comment by jedireza** [comment]
There's been a discussion about Babel 6 in that repo: https://github.com/nlf/lab-babel/pull/6

And a new section added to the README: https://github.com/nlf/lab-babel#babel--6

**Comment by AdrieanKhisbe** [comment]
Thanks for the pointer. 
That was what I read, and try to apply with no success. :/

(`ncu -u ; npm install --save-dev babel-preset-es2015; npm test` -> the error)

**Comment by jedireza** [comment]
Sorry for closing the issue so fast. I created another PR and asked one of the `lab-babel` devs for help.

**Comment by AdrieanKhisbe** [comment]
No problem :)

**Pull request closed without merging**
