### PR TITLE
WIP: Using Babel 6

### PR DESCRIPTION
**Pull request by jedireza**
Continuing from #2 cc/ @AdrieanKhisbe

@phated, any ideas on what we could be doing wrong here? It doesn't seem like the transform is happening. If I use `lab-babel@1.0.0` I don't get the same error.

```bash
$ npm test

> lab-es6@1.0.0 test /home/jedireza/projects/lab-es6
> lab -t 100 -S -T ./node_modules/lab-babel ./test/src/

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jedireza/projects/lab-es6/node_modules/lab/lib/coverage.js:36:28)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/jedireza/projects/lab-es6/node_modules/lab/lib/cli.js:106:25
    at Array.forEach (native)
    at Object.internals.traverse.paths.forEach.testFiles [as traverse] (/home/jedireza/projects/lab-es6/node_modules/lab/lib/cli.js:102:19)
    at Object.exports.run (/home/jedireza/projects/lab-es6/node_modules/lab/lib/cli.js:51:31)
    at Object.<anonymous> (/home/jedireza/projects/lab-es6/node_modules/lab/bin/lab:5:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

### CODE REVIEW

**Comment by phated** [comment]
Adding the babelrc to your own project will do the trick. It doesn't need to be in this project

**Comment by phated** [comment]
The problem you are seeing is actually the lab library. They have been switching hapi modules to complete es6 (terrible idea, imo) so you can't be using latest unless you are on node 4+

**Comment by jedireza** [comment]
Yes I'm using node `4.2.x`. This repo is just an example project not a module so the `.babelrc` file in this PR should be doing the job.

**Comment by phated** [comment]
@jedireza I actually found the issue and will be fixing it in lab-babel shortly

**Comment by phated** [comment]
@jedireza looks like you've already updated :stuck_out_tongue:  - seems to be working for me now

**Comment by jedireza** [comment]
:boom: Thanks @phated!

**Comment by phated** [comment]
Np!  thanks for catching this

**Comment by AdrieanKhisbe** [comment]
Thanks @everyone :) :clap:

**Pull request merged**
